### ISSUE TITLE
Please document the enums

### ISSUE THREAD

**Issue by ryanpeach** [TYPEmber/ndarray-conv#1]
Some of the enum types are not clear. Like, what is the difference between Circular, Reflect, and Replicate?

If the repo is stable, I'd just apply the following macros to it and document it fully.

```
#![warn(missing_docs)]
#![warn(clippy::missing_docs_in_private_items)]
```

**Comment by TYPEmber** [comment]
Thank you for your attention to this project, I'm working hard on a new version with incompatible interface.
Therefore, if you wish, you can add these macros to this repo after a version update.

Best wishes!

**Comment by TYPEmber** [comment]
The new version(0.3.0) has done, feel free to document it if you still have interest.
And these enums are aligned with PyTorch's conv2d:https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html

**Comment by deavid** [comment]
The differences between Circular, Reflect and Replicate are, if I understood correctly:

Let's assume `12345` as the signal to convolute (5 elements: 1,2,3,4,5)

* Circular:  `12345[12345]12345`
* Reflect: `5432[12345]4321`
* Replicate: `1111[12345]5555`

For this, you need to imagine that you're accessing an `idx` that goes from -kernel_half_len to signal_len + kernel_half_len. So for a signal of size 10 and a kernel of 5, you'll be accessing the signal from -2..11; so the problem is, what values do you put there.

Circular assumes the signal is circular, that follows `idx % len`, so when it ends, it starts over.

Reflect makes a mirror reflection after the end and before the beginning. So for `idx<0` it will read `-idx`. For `idx>=len`, it will access `len-idx%len-1` (more or less, my math here is lacking)

Replicate just takes the closest value: `idx.clamp(0, len-1)`

**Comment by TYPEmber** [comment]
I have read your email. If possible, you can directly submit a PR regarding the documentation, and I would be happy to merge it into the master branch.

**Comment by deavid** [comment]
Done. See https://github.com/TYPEmber/ndarray-conv/pull/4

**Comment by TYPEmber** [comment]
I will make some more modifications and release a new version. Thank you for your contribution to the documentation.
